### ISSUE TITLE
Disable I2C / Enable CAN0/CAN1

### ISSUE THREAD

**Issue by Sefiroth1981** [RobertCNelson/dtb-rebuilder#13]
Hello,

I need both can-interfaces of the beaglebone black. On Debian Wheezy with 3.8.13 Kernel I could change the device tree to disable i2c2 and enable can0/can1 during the boot process.

Now, on Debian Jessie with 4.4.9-ti-r25 Kernel it doesn't work. Can you explain me, how to change the device tree? 

I tried to add the changes in am335x-bone-common.dtsi similar I changed it at 3.8.13 and executed
make
make install

But after reboot can doesn't work. The Beaglebone neither sends nor receives can messages (testet with candump and cansend from can-utils).

Best regards,
Andre

**Comment by Lemon-zz** [comment]
Hi
I`ve got same problem. Here the solution:
File:
**/dtb-rebuilder/src/arm/am335x-bone-common.dtsi**
line 

```
&i2c2 {
    status = "okay";
    pinctrl-names = "default";
    pinctrl-0 = <&i2c2_pins>;
```

Need to be comment out  "**pinctrl-0 = <&i2c2_pins>**;" like:

```
&i2c2 {
    status = "okay";
    pinctrl-names = "default";
//    pinctrl-0 = <&i2c2_pins>;
```

Seem`s to be working to me. Maybe should change "okay" to "disabled".
