### ISSUE TITLE
DCAN0 Issues / Disabling I2C2

### ISSUE THREAD

**Issue by altr0n** [RobertCNelson/dtb-rebuilder#21]
Hello,

First of all, I apologize if this is not the appropriate place to pose this question, I've dug around for some time now looking for a solution but have not found a working one.

I also tried the solution outlined [here](https://github.com/RobertCNelson/dtb-rebuilder/issues/13) with no luck.

I am working on the BeagleBone Black, Kernel version 4.9 from your bb-kernel repo.

I would like to use the two CAN controllers on the SoC as described in the following article:

http://www.embedded-things.com/bbb/enable-canbus-on-the-beaglebone-black/

I know that in order to do this I need to disable i2c2 which will disable automatic cape detection (which is not a problem for me) When I uncomment the following line: [here](https://github.com/RobertCNelson/dtb-rebuilder/blob/4.9.x/src/arm/am335x-bone-common.dtsi#L243) and rebuild/reinstall the device tree. I also built and installed a DTB for using DCAN0 and I am able to bring up a second CAN interface on DCAN0, however I am not seeing and CAN traffic over this interface. I've tested the transceiver and I am able to view the traffic over DCAN1 so I don't think this an issue with the network. Is there some other thing that I might be missing in order to enable DCAN0?

I noticed that when I use the config-pin tool, that the pins I am using for DCAN1 show up as the following:
```
root@beaglebone:/home/debian# config-pin -l P9_24
default gpio gpio_pu gpio_pd uart can i2c pru_uart pruin
root@beaglebone:/home/debian# config-pin -l P9_26
default gpio gpio_pu gpio_pd uart can i2c pru_uart pruin
```

And when I try for DCAN0, I see slightly different output:

```
root@beaglebone:/home/debian# config-pin -l P9_21
default gpio gpio_pu gpio_pd spi uart i2c pwm pru_uart
root@beaglebone:/home/debian# config-pin -l P9_22
default gpio gpio_pu gpio_pd spi uart i2c pwm pru_uart
```

Note that the ```can``` option does not show up.

I2C2 Has been disabled, and the CAN interface is present, however no traffic is present when I try to read from the interface. I've tested the transceivers and the network to make sure there are no issues there, am I missing something else here? Is it possible to use both DCAN interfaces?

**Comment by altr0n** [comment]
Turns out that this was an issue on my part - sorry to flood the issue list with this. The solution was that I was not properly naming my DTB file for DCAN0 before putting it into /lib/firmware.

In case anyone stumbles upon this in the future, the DTS file that I used for CAN0 came from [here](https://github.com/oniongarlic/bbb-can.git)

Perhaps it might be a good idea to add a DCAN0 DTS to this [repo](https://github.com/RobertCNelson/bb.org-overlays/)?

**Comment by RobertCNelson** [comment]
@altr0n yeah with the move to u-boot overlays, we can start disabling this i2c port as default and let the user choose which option they want thru config-pin (or a custom overlay)..

I'm thinking v4.14.x-lts might be a good time to do the switch. ;)

Regards,

**Comment by altr0n** [comment]
Ah ok, thank you for clarifying. I thought I was missing something when ```can``` didn't show up in the ```config-pin``` output. Thanks again for the help and all the tools!
