### ISSUE TITLE
How to add target to build?

### ISSUE THREAD

**Issue by lthiery** [RobertCNelson/dtb-rebuilder#24]
Forgive me but I've never used some a build system before. I'm reading through the Makefile and trying to understand where the target list comes from. The reason is, I'd like to make my own overlay it's own target rather than hijacking someone else's, as I am going to have a few different overlays in the future.

Let's say I make a copy of `src/arm/am335x-boneblack-wireless-robotiscape.dts` called `src/arm/am335x-boneblack-target1.dts`

How do I add that that new target to the build system?

**Comment by RobertCNelson** [comment]
```
cp src/arm/am335x-boneblack-wireless-robotiscape.dts src/arm/am335x-boneblack-target1.dts
make
```

**Comment by lthiery** [comment]
Neat. What's this general build system called? I've never had something be smart enough to generate targets like that

**Comment by RobertCNelson** [comment]
it's part of kernel.org's kbuild...

**Comment by lthiery** [comment]
Cool - I guess I'll dig into that world when I have a moment. Thank you for your help
