### ISSUE TITLE
How do I compile a proper overlay for vmlinuz-3.8.13-xenomai-r83

### ISSUE THREAD

**Issue by lthiery** [RobertCNelson/dtb-rebuilder#25]
Hi there,

I'm trying to re-purpose the I2C2 pins on the Beaglebone Black such that they can be used for UART flow control. (I realize that they are used for cape management and are supposed to read EEPROM bytes, but I won't be using capes for my project where I need flow control on UART1 instead). 

I might be wrong, but I figured the easiest way to do this is to change the overlay. 

I've noticed that in both the old `3.19.x/src/arm/am335x-bone-common.dtsi` and the more recent `4.4-ti/src/arm/am335x-bone-common-no-capemgr.dtsi`, i2c2 grabs those pins. I was going to edit those to remove i2c2 in favor of uart1 with flow control.

However, I can't even get started with a base case where I simply load `src/arm/am335x-boneblack.dtb` compiled by me with no changes. Every single dtb I build just crashes on kernel loading. I think the core issue is that I'm using `3.8.13` (the most recent BBB release image on their website) but this project doesn't have a branch for that release. I'm using branch `3.19.x` and it fails. But maybe it's something entirely different...

For reference, here is the output I get over UART0

```Loaded environment from /boot/uEnv.txt
debug: [dtb=../home/machinekit/dtb-rebuilder/src/arm/am335x-boneblack.dtb] ...
Using: dtb=../home/machinekit/dtb-rebuilder/src/arm/am335x-boneblack.dtb ...
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-3.8.13-xenomai-r83 ...
5740648 bytes read in 379 ms (14.4 MiB/s)
loading /boot/../home/machinekit/dtb-rebuilder/src/arm/am335x-boneblack.dtb ...
87161 bytes read in 223 ms (380.9 KiB/s)
uboot_overlays: add [enable_uboot_overlays=1] to /boot/uEnv.txt to enable...
loading /boot/initrd.img-3.8.13-xenomai-r83 ...
3653158 bytes read in 247 ms (14.1 MiB/s)
debug: [console=ttyO0,115200n8 capemgr.disable_partno=BB-BONELT-HDMI root=UUID=869f8624-d2b6-47bb-aabb-4193203235a7 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet cape_universal=enable] ...
debug: [bootz 0x82000000 0x88080000:37be26 0x88000000] ...
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to 8fc84000, end 8ffffe26 ... OK
   Loading Device Tree to 8fc6b000, end 8fc83478 ... OK

Starting kernel ...

Uncompressing Linux... done, booting the kernel.
```

Here it hangs until the watchdog timer resets the system. This is opposed to a default boot up:

```
Loaded environment from /boot/uEnv.txt
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-3.8.13-xenomai-r83 ...
5740648 bytes read in 380 ms (14.4 MiB/s)
loading /boot/dtbs/3.8.13-xenomai-r83/am335x-boneblack.dtb ...
26118 bytes read in 21 ms (1.2 MiB/s)
uboot_overlays: add [enable_uboot_overlays=1] to /boot/uEnv.txt to enable...
loading /boot/initrd.img-3.8.13-xenomai-r83 ...
3653158 bytes read in 247 ms (14.1 MiB/s)
debug: [console=ttyO0,115200n8 capemgr.disable_partno=BB-BONELT-HDMI root=UUID=869f8624-d2b6-47bb-aabb-4193203235a7 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet cape_universal=enable] ...
debug: [bootz 0x82000000 0x88080000:37be26 0x88000000] ...
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to 8fc84000, end 8ffffe26 ... OK
   Loading Device Tree to 8fc7a000, end 8fc83605 ... OK

Starting kernel ...

Uncompressing Linux... done, booting the kernel.
[    0.384191] omap2_mbox_probe: platform not supported
[    0.546604] tps65217-bl tps65217-bl: no platform data provided
[    0.606427] bone-capemgr bone_capemgr.9: slot #0: No cape found
[    0.643529] bone-capemgr bone_capemgr.9: slot #1: No cape found
[    0.680642] bone-capemgr bone_capemgr.9: slot #2: No cape found
[    0.717751] bone-capemgr bone_capemgr.9: slot #3: No cape found

...

```

I have noticed for one that my overlay is much bigger: 87161 vs 26118 bytes...

Any ideas of how I can get through this?

**Comment by RobertCNelson** [comment]
For 3.8.x based kernel overlays, it's best to just rebuild the overlay with the kernel build. (as they were built-in by default in the firmware directory.)

Regards,

PS, 3.8.x is considered EOL...

**Comment by RobertCNelson** [comment]
PS2, what you are trying todo is already enabled by default with the lastest kernel/image..

https://rcn-ee.net/rootfs/bb.org/testing/2017-12-17/

https://github.com/RobertCNelson/ti-linux-kernel-dev/blob/ti-linux-4.9.y/patches/config_pin/0001-am335x-bone-common-config-pin-carve-out-P9.19-P9.20.patch

```
config-pin P9_19 uart
config-pin P9_20 uart
```

**Comment by lthiery** [comment]
Ah thank you again for your help! The official BBB website is still rolling that 3.8 kernel which is a shame if its EOL'ed

I'll try one of those newer images. config-pin P9_19 was exactly what I attempted at first but it prohibited me from doing so. Glad to hear you guys are so ahead on this! Patch from end of Oct already :+1: 

Side-note: what's the difference on all these images? I understand that they are different configurations for different applications but is there a place where I can see what iot vs lxqt vs machinekit is?
