### ISSUE TITLE
SGX is disabled in am335x-boneblack-uboot-univ but enabled in am335x-boneblack-uboot

### ISSUE THREAD

**Issue by ThatWileyGuy** [RobertCNelson/dtb-rebuilder#32]
I'm working on getting SGX working on your most recent Ubuntu 18.04 flasher image (kernel is 4.14.67-ti-r74), and I've found two things that might be bugs:
- U-Boot always loads am335x-boneblack-uboot-univ.dtb as the base tree, even if enable_uboot_cape_universal is 0
- am335x-boneblack-uboot-univ.dtb does not enable SGX (which seems to be the only difference when comparing to am335x-boneblack-uboot.dtb)

Copying am335x-boneblack-uboot.dtb over am335x-boneblack-uboot-univ.dtb results in a running system with SGX enabled and seemingly no new issues.

What is the intended behavior here? Is the issue that I'm supposed to turn off the universal cape to get SGX but that switch isn't working, is it that the universal cape should enable SGX, or is there some other way to resolve this?

version info:
```
git:/opt/scripts/:[d9a7ff1063db8359841c0349caf0898fd0bbc452]
eeprom:[A335BNLT00C02916BBBK16F0]
model:[TI_AM335x_BeagleBone_Black]
dogtag:[Umikaze 2.2.1-1804test4 Thu Dec 13 02:59:58 UTC 2018]
bootloader:[eMMC-(default)]:[/dev/mmcblk1]:[U-Boot 2018.09-00002-g0b54a51eee]:[location: dd MBR]
kernel:[4.14.67-ti-r74]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-UIO-00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1]
pkg check: to individually upgrade run: [sudo apt install --only-upgrade <pkg>]
pkg:[bb-cape-overlays]:[4.4.20181120.0-0rcnee0~bionic+20181120]
pkg:[bb-wl18xx-firmware]:[1.20180517-0rcnee0~bionic+20180517]
pkg:[kmod]:[24-1ubuntu3.1rcnee0~bionic+20181120]
WARNING:pkg:[librobotcontrol]:[NOT_INSTALLED]
groups: ‘ubuntu’: no such user
groups:[]
cmdline:[console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk1p1 ro rootfstype=ext4 rootwait uboot_detected_capes=BB-BONE-REPLICAP, coherent_pool=1M net.ifnames=0 quiet consoleblank=0 fbcon=rotate:1 omap_wdt.nowayout=0]
dmesg | grep pinctrl-single
[    1.206031] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568
[    1.458878] pinctrl-single 44e10800.pinmux: pin PIN101 already requested by 481a0000.spi; cannot claim for 48038000.mcasp
[    1.470203] pinctrl-single 44e10800.pinmux: pin-101 (48038000.mcasp) status -22
[    1.477691] pinctrl-single 44e10800.pinmux: could not request pin 101 (PIN101) from group mcasp0_pins  on device pinctrl-single
dmesg | grep gpio-of-helper
[    1.207560] gpio-of-helper ocp:cape-universal: ready
END
```

**Comment by RobertCNelson** [comment]
@ThatWileyGuy no, that's a bug, SGX should be enabled across the board in the ti kernel.. I'll fix that.

To disable enable_uboot_cape_universal, just comment it out, as the value of "1" doesn't mean anything, u-boot is just looking if the variable is defined..

Regards,

**Comment by ThatWileyGuy** [comment]
Awesome, thanks so much!
