### ISSUE TITLE
Cannot set up serial on BBB

### ISSUE THREAD

**Issue by AdamSLevy** [RobertCNelson/dtb-rebuilder#5]
I am running Linux arm 3.14.41-ti-r63 #1 SMP PREEMPT Thu May 7 18:58:43 UTC 2015 armv7l armv7l armv7l GNU/Linux on beaglebone black. I am using the image from this page: http://elinux.org/BeagleBoardUbuntu#eMMC:_BeagleBone_Black

After successfully running

```
$ make all
$ sudo make install
```

I still cannot see my serial devices.

```
ubuntu@arm:~/dtb$ sudo setserial -g /dev/ttyO*
/dev/ttyO0, UART: 8250, Port: 0x0000, IRQ: 88
/dev/ttyO1, UART: 8250, Port: 0x0000, IRQ: 89
/dev/ttyO2, UART: 8250, Port: 0x0000, IRQ: 90
/dev/ttyO4, UART: 8250, Port: 0x0000, IRQ: 61
/dev/ttyO5, UART: 8250, Port: 0x0000, IRQ: 62
```

**Comment by RobertCNelson** [comment]
"/dev/ttySx"

**Comment by RobertCNelson** [comment]
and don't forget to 'un-comment" the serial port you want..

https://github.com/RobertCNelson/dtb-rebuilder/blob/3.14-ti/src/arm/am335x-boneblack.dts#L88
