### ISSUE TITLE
Still no serial on BBB with 3.14.41

### ISSUE THREAD

**Issue by AdamSLevy** [RobertCNelson/dtb-rebuilder#6]
Thanks for your help so far. Still no luck though.

The make all and sudo make install went through just fine. The includes for uart 1 and 2 are uncommented.

Still no serial port:

```
ubuntu@arm:~$ sudo setserial -g /dev/ttyO*
[sudo] password for ubuntu: 
/dev/ttyO0, UART: 8250, Port: 0x0000, IRQ: 88
/dev/ttyO1, UART: 8250, Port: 0x0000, IRQ: 89
/dev/ttyO2, UART: 8250, Port: 0x0000, IRQ: 90
/dev/ttyO4, UART: 8250, Port: 0x0000, IRQ: 61
/dev/ttyO5, UART: 8250, Port: 0x0000, IRQ: 62
ubuntu@arm:~$ sudo setserial -g /dev/ttyS*
/dev/ttyS0, UART: 8250, Port: 0x0000, IRQ: 88
/dev/ttyS1, UART: 8250, Port: 0x0000, IRQ: 89
/dev/ttyS2, UART: 8250, Port: 0x0000, IRQ: 90
/dev/ttyS3, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS4, UART: 8250, Port: 0x0000, IRQ: 61
/dev/ttyS5, UART: 8250, Port: 0x0000, IRQ: 62
/dev/ttyS6, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS7, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS8, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS9, UART: unknown, Port: 0x0000, IRQ: 0
ubuntu@arm:~$ uname -a
Linux arm 3.14.41-ti-r63 #1 SMP PREEMPT Thu May 7 18:58:43 UTC 2015 armv7l armv7l armv7l GNU/Linux
```

**Comment by RobertCNelson** [comment]
So you changed:

```
/* uart1: P9.24, P9.26 */
#include "am335x-ttyO1.dtsi"
/* #include "am335x-bone-ttyO1.dtsi" */
/* uart2: P9.21, P9.22 */
#include "am335x-ttyO2.dtsi"
/* #include "am335x-bone-ttyO2.dtsi" */
```

to:

```
/* uart1: P9.24, P9.26 */
#include "am335x-ttyO1.dtsi"
#include "am335x-bone-ttyO1.dtsi"
/* uart2: P9.21, P9.22 */
#include "am335x-ttyO2.dtsi"
#include "am335x-bone-ttyO2.dtsi"
```

Then ran:

```
make
sudo make install
sudo reboot
```

Which will enable /dev/ttyS1 & /dev/ttyS2..

Regards,

**Comment by AdamSLevy** [comment]
I did exactly that. Those lines were in the file src/arm/am335x-boneblack.dts 

Still no serial port.

Let me know what further information would be helpful.

I am running this on an element14 BBB Rev C. Everything is up to date.

**Comment by RobertCNelson** [comment]
Actually it's not up to date.

```
sudo apt-get update
sudo apt-get install linux-image-3.14.43-ti-r67
sudo reboot
```

Or via these directions: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#Kernel_Upgrade

Then rerun

```
make
sudo make install
```

Other then that, not much more to really debug. So either you did above or you didn't.

```
dmesg | grep serial
```

and you should see something like:

```
[    2.453706] 4806a000.serial: ttyS0 at MMIO 0x4806a000 (irq = 104, base_baud = 3000000) is a 8250
[    2.454250] 4806c000.serial: ttyS1 at MMIO 0x4806c000 (irq = 105, base_baud = 3000000) is a 8250
[    2.454824] 48020000.serial: ttyS2 at MMIO 0x48020000 (irq = 106, base_baud = 3000000) is a 8250
```

(ignore the actual xyz.serial numbers, as that is omap5 with the same kernel..)

For element 14 boards, please use the beagleboard forum:
https://groups.google.com/forum/#!forum/beagleboard

Regards,

**Comment by AdamSLevy** [comment]
I won't open another issue on it but I have followed these directions exactly with no success. 

After searching around I found that you recommended to someone else that they set dtb=am335x-boneblack.dtb in /boot/uEnv.txt 

I tried that. No luck. 

I tried setting dtb=am335x-boneblack-ttyO1.dtb

But after a reboot I could no longer ssh in over ethernet so I had to reimage.

I am opting for a usb-serial converter for my project but I am still disappointed that I cannot access my serial ports. 

Here is my output from dmesg

```
doas@arm:~$ dmesg | grep tty
[    0.000000] Kernel command line: console=ttyO0,115200n8 root=UUID=60139904-a2d5-4622-9490-862c426eb323 ro rootfstype=ext4 rootwait fixrtc coherent_pool=1M quiet
[    0.000424] WARNING: Your 'console=ttyO0' has been replaced by 'ttyS0'
[    2.655376] 44e09000.serial: ttyS0 at MMIO 0x44e09000 (irq = 88, base_baud = 3000000) is a 8250
[    2.673292] console [ttyS0] enabled
[    2.674295] 48022000.serial: ttyS1 at MMIO 0x48022000 (irq = 89, base_baud = 3000000) is a 8250
[    2.675125] 48024000.serial: ttyS2 at MMIO 0x48024000 (irq = 90, base_baud = 3000000) is a 8250
[    2.675931] 481a8000.serial: ttyS4 at MMIO 0x481a8000 (irq = 61, base_baud = 3000000) is a 8250
[    2.676719] 481aa000.serial: ttyS5 at MMIO 0x481aa000 (irq = 62, base_baud = 3000000) is a 8250
```

I know you are a busy man and have put a lot of work into this. I appreciate your help thus far and all the work you've done. If you get around to looking at this and have another suggestion I'm all ears.

Thank you

**Comment by RobertCNelson** [comment]
They are clearly enabled: /dev/ttyS1 & /dev/ttyS2

```
[    2.674295] 48022000.serial: ttyS1 at MMIO 0x48022000 (irq = 89, base_baud = 3000000) is a 8250
[    2.675125] 48024000.serial: ttyS2 at MMIO 0x48024000 (irq = 90, base_baud = 3000000) is a 8250
```

Fix your software.

**Comment by cPhil** [comment]
Sorry I know this is marked as closed, but pertaining to this thread, the am335x-boneblack.dts file refers to ttyO\* while the dmesg shows ttyS\* enabled. Is this expected behavior? 

Thanks for all the help Robert!

**Comment by RobertCNelson** [comment]
Yes, 
http://git.ti.com/gitweb/?p=ti-linux-kernel/ti-linux-kernel.git;a=commit;h=37de5ba0b14821b1a439ce635ae8551bdc16af54

**Comment by cPhil** [comment]
Thanks!
